# Generated by Django 3.0.4 on 2020-03-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200329_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prsnl',
            options={'verbose_name': 'personnel', 'verbose_name_plural': 'personnel'},
        ),
        migrations.AddField(
            model_name='prsnl',
            name='position',
            field=models.CharField(choices=[('P01', 'Physician - General Medicine'), ('P02', 'Physician - Critical Care'), ('P03', 'Physician - Emergency'), ('N01', 'Nurse'), ('N02', 'Nurse - ICU'), ('N03', 'Nurse - Emergency'), ('N04', 'Nurse - Ambulatory'), ('CEO', 'Chief Executive Officer'), ('CFO', 'Chief Financial Officer'), ('COO', 'Chief Operating Officer'), ('M01', 'General Manager')], default='N01', max_length=3),
        ),
    ]
