# Generated by Django 3.0.4 on 2020-03-30 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200329_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name_last'], 'verbose_name': 'Person'},
        ),
        migrations.AlterModelOptions(
            name='prsnl',
            options={'verbose_name': 'Personnel', 'verbose_name_plural': 'Personnel'},
        ),
    ]
