# Generated by Django 3.0.4 on 2020-03-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='id',
            new_name='question_id',
        ),
    ]
