# Generated by Django 3.0.3 on 2020-03-03 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_value',
            name='definition',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code_value',
            name='description',
            field=models.CharField(default='thid', max_length=60),
            preserve_default=False,
        ),
    ]
