# Generated by Django 3.0.3 on 2020-03-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200302_2222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code_Value',
            new_name='CodeValue',
        ),
        migrations.RenameModel(
            old_name='Person_Alias',
            new_name='PersonAlias',
        ),
    ]
