# Generated by Django 3.0.3 on 2020-03-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200302_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='code_value',
            name='display',
            field=models.CharField(default='display', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code_value',
            name='display_key',
            field=models.CharField(default='displaykey', max_length=40),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='code_value',
            index=models.Index(fields=['code_set', 'display_key'], name='polls_code__code_se_f6ff3c_idx'),
        ),
    ]
