# Generated by Django 3.0.3 on 2020-03-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200302_2250'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='code_value',
            name='code_set',
        ),
        migrations.RemoveIndex(
            model_name='code_value',
            name='display_key',
        ),
        migrations.AddIndex(
            model_name='code_value',
            index=models.Index(fields=['code_set'], name='code_set_idx'),
        ),
        migrations.AddIndex(
            model_name='code_value',
            index=models.Index(fields=['display_key'], name='display_key_idx'),
        ),
    ]
